# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Sentinel2Helper
                                 A QGIS plugin
 This plugin downloads Sentinel-2 data and processes it to Level-2A
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-09-12
        copyright            : (C) 2019 by Patrick Sogno
        email                : patrick.sogno@stud-mail.uni-wuerzburg.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Sentinel2Helper class from file Sentinel2Helper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Sen2Helper import Sentinel2Helper
    return Sentinel2Helper(iface)
